title: Coffee Journal
description: Personal coffee brewing & tasting journal
markdown: kramdown
permalink: pretty

# IMPORTANT for project pages
baseurl: /coffee-test
url: https://truedevopsmk-lab.github.io

plugins:
  - jekyll-seo-tag
