title: Coffee Journal
description: Personal coffee brewing & tasting journal
theme: minima
markdown: kramdown
permalink: pretty

baseurl: /coffee-test
url: https://truedevopsmk-lab.github.io

plugins:
  - jekyll-seo-tag
